#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias vim="mvim"
alias git="hub"
alias rm="trash"
alias emacs="emacsclient -nc"
alias magit="emacsclient -nc --eval '(magit-status)'"

function md() {
	mkdir -p "$@"  && cd $_
}
